baseURL = 'https://lewisdraper.github.io/'
languageCode = 'en-us'
title = "Lewis Draper"
theme="ananke"
paginate = 5000 #frontpage pagination
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
omit_header_text = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/LewisGamedev"
  instagram = ""
  youtube = ""
  github = "https://github.com/lewisdraper"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lewis-draper-638011126"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/frontpage/Liverpool-skyline_X1650-1630x983.jpg"
  recent_posts_number = 2